Repository order-desk/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#22 Update contributions.md
  contributions.md
Labels: hacktoberfest-accepted

#25 Update contributions.md
  contributions.md
Labels: hacktoberfest-accepted

#27 Update contributions.md
  contributions.md
Labels: hacktoberfest-accepted

#37 Add website link to navigation
  _data/navigation.yml
Labels: hacktoberfest, hacktoberfest-accepted

#36 Delete CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted

#34 Delete FUNDING.yml
  .github/FUNDING.yml
Labels: hacktoberfest, hacktoberfest-accepted

#39 Site info
  _config.yml
  images/OD-Logo.png
Labels: bug, hacktoberfest

#43 Update contributions.md
  contributions.md
Labels: hacktoberfest-accepted

#44 Louie did a copy edit of the Shopify/ShipBob blog post, Issue #9
  contributions.md
Labels: hacktoberfest-accepted
